---
stages:
- name: AdapterBuild
  inputs:
  - url: https://git.ng.bluemix.net/shinoj.zacharias/MFP80DevOps.git
    type: git
    branch: master
    service: ${SAMPLE_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # To use Node.js 6.7.0, uncomment the following line:
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      echo "#### npm install -g mfpdev-cli"
      npm install -g mfpdev-cli
      echo "#### mfpdev --version"
      mfpdev --version
      echo "#### cd adapters/JavaAdapter"
      cd adapters/JavaAdapter
      echo "#### Build the adapter : mfpdev adapter build"
      mfpdev adapter build
- name: AdapterDeploy
  inputs:
  - type: job
    stage: AdapterBuild
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: INSTANCE_NAME
    value: mfp-sz-test
    type: text
  jobs:
  - name: DeployAdapter
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: "#!/bin/bash\nset -x\n# To use Node.js 6.7.0, uncomment the following\
      \ line:\nexport PATH=/opt/IBM/node-v6.7.0/bin:$PATH\n\necho \"Getting server\
      \ and credentials\"\n# get mfpserver url, username and password\n\n credentials=$(cf\
      \ service-key $INSTANCE_NAME Credentials-1)\n echo \"Credentials: $credentials\"\
      \n password=$(echo $credentials | grep \\\"password\\\": | awk -F \"\\\"password\\\
      \": \" '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\\(.*\\)/\\1/' | sed\
      \ 's/\\(.*\\)./\\1/')\n echo \"Password: $password\"\n url=$(echo $credentials\
      \ | grep \\\"url\\\": | awk -F \"\\\"url\\\": \" '{print $2 }' | awk -F , '{print\
      \ $1 }' | sed 's/.\\(.*\\)/\\1/' | sed 's/\\(.*\\)./\\1/' | sed -e 's/https/http/g')\
      \ \n echo \"URL: $url\"\n user=$(echo $credentials | grep \\\"user\\\": | awk\
      \ -F \"\\\"user\\\": \" '{print $2 }' | awk -F , '{print $1 }' | awk -F \\ \
      \ '{print $1 }'| sed 's/.\\(.*\\)/\\1/' | sed 's/\\(.*\\)./\\1/')\n echo \"\
      User: $user\"\n\nurl=$url:80\necho \"#### npm install -g mfpdev-cli\"\nnpm install\
      \ -g mfpdev-cli\necho \"#### mfpdev --version\"\nmfpdev --version\necho \"####\
      \ cd adapters/JavaAdapter\"\ncd adapters/JavaAdapter\necho \"#### adding server\
      \ definition\"\nmfpdev server add server1 --url $url --login $user --password\
      \ $password --setdefault\necho \"#### Deploy Adapter : mfpdev adapter deploy\"\
      \nmfpdev adapter deploy\n"
- name: AdapterTest-UnitTests
  inputs:
  - url: https://git.ng.bluemix.net/shinoj.zacharias/MFP80DevOps.git
    type: git
    branch: master
    service: ${SAMPLE_REPO}
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: INSTANCE_NAME
    value: mfp-sz-test
    type: text
  jobs:
  - name: TestAdapter
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: "#!/bin/bash\nset -x\n# To use Node.js 6.7.0, uncomment the following\
      \ line:\nexport PATH=/opt/IBM/node-v6.7.0/bin:$PATH\n\necho \"Getting server\
      \ and credentials\"\n# get mfpserver url, username and password\n\n credentials=$(cf\
      \ service-key $INSTANCE_NAME Credentials-1)\n echo \"Credentials: $credentials\"\
      \n password=$(echo $credentials | grep \\\"password\\\": | awk -F \"\\\"password\\\
      \": \" '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\\(.*\\)/\\1/' | sed\
      \ 's/\\(.*\\)./\\1/')\n echo \"Password: $password\"\n url=$(echo $credentials\
      \ | grep \\\"url\\\": | awk -F \"\\\"url\\\": \" '{print $2 }' | awk -F , '{print\
      \ $1 }' | sed 's/.\\(.*\\)/\\1/' | sed 's/\\(.*\\)./\\1/' | sed -e 's/https/http/g')\
      \ \n echo \"URL: $url\"\n user=$(echo $credentials | grep \\\"user\\\": | awk\
      \ -F \"\\\"user\\\": \" '{print $2 }' | awk -F , '{print $1 }' | awk -F \\ \
      \ '{print $1 }'| sed 's/.\\(.*\\)/\\1/' | sed 's/\\(.*\\)./\\1/')\n echo \"\
      User: $user\"\n\nurl=$url:80\necho \"#### npm install -g mfpdev-cli\"\nnpm install\
      \ -g mfpdev-cli\necho \"#### mfpdev --version\"\nmfpdev --version\necho \"####\
      \ adding server definition\"\nmfpdev server add server1 --url $url --login $user\
      \ --password $password --setdefault\n\necho \"#### cd adapters/JavaAdapter/tests\"\
      \ncd adapters/JavaAdapter/tests\necho \"#### Testing Adapter Endpoints\"\n./resource.sh\n\
      ./resource_greet.sh\n./resource_protected.sh\n./resource_testpost.sh"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
