---
stages:
- name: MyStage
  properties:
  - name: INSTANCE_NAME
    value: mfp-sz-test
    type: text
  jobs:
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    target:
      region_id: ibm:yp:us-south
      organization: shinoj.zacharias@in.ibm.com
      space: dev
      application: MFP80DevOps
    script: |-
      #!/bin/bash
            token=$(cf oauth-token | awk '{print $2}')
            json={\"deploy\":\"true\",\"name\":\"$INSTANCE_NAME\",\"token\":\"$token\"}
            echo "Input: $json"
            cf cs "Mobile Foundation" Developer $INSTANCE_NAME -c $json
            echo "Created Service Instance"
            sleep 1m
            cf create-service-key $INSTANCE_NAME Credentials-1
            echo "Created Service Keys"
            credentials=$(cf service-key $INSTANCE_NAME Credentials-1)
            echo "Credentials: $credentials"
            password=$(echo $credentials | grep \"password\": | awk -F "\"password\": " '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
            echo "Password: $password"
            url=$(echo $credentials | grep \"url\": | awk -F "\"url\": " '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
            echo "URL: $url"
            user=$(echo $credentials | grep \"user\": | awk -F "\"user\": " '{print $2 }' | awk -F , '{print $1 }' | awk -F \  '{print $1 }'| sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
            echo "User: $user"
            until $(curl --output /dev/null --silent --head --fail $url/mfpconsole); do
              printf '.'
              sleep 5
            done
            # Deploying the confidential client
            curl -u $user:$password -X PUT -H "Content-Type: application/json" -d '{"clients":[{"id":"test","displayName":"Test","secret":"test","allowedScope":"*"},{"id": "admin","displayName": "admin","secret": "darwIn$hfr","allowedScope": "push.* mfp.admin.plugins settings.read"},{"id": "push","displayName": "push","secret": "darwIn$hfr","allowedScope": "authorization.introspect"}]}' $url/mfpadmin/management-apis/2.0/runtimes/mfp/confidentialclients
            exit
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish

