---
stages:
- name: mfp-service-create
  properties:
  - name: INSTANCE_NAME
    value: MFP-Test-123
    type: text
  jobs:
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    target:
      region_id: ibm:yp:us-south
      organization: sachinnayak@in.ibm.com
      space: dev
      application: mfp-service-create
    script: |-
      #!/bin/bash
      token=$(cf oauth-token | awk '{print $2}')
      json={\"deploy\":\"true\",\"name\":\"$INSTANCE_NAME\",\"token\":\"$token\"}
      echo "Input: $json"
      cf cs "Mobile Foundation" Developer $INSTANCE_NAME -c $json
      echo "Created Service Instance"
      sleep 1m
      cf create-service-key $INSTANCE_NAME Credentials-1
      echo "Created Service Keys"
      credentials=$(cf service-key $INSTANCE_NAME Credentials-1)
      echo "Credentials: $credentials"
      password=$(echo $credentials | grep \"password\": | awk -F "\"password\": " '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
      echo "Password: $password"
      url=$(echo $credentials | grep \"url\": | awk -F "\"url\": " '{print $2 }' | awk -F , '{print $1 }' | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
      echo "URL: $url"
      user=$(echo $credentials | grep \"user\": | awk -F "\"user\": " '{print $2 }' | awk -F , '{print $1 }' | awk -F \  '{print $1 }'| sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/')
      echo "User: $user"
      until $(curl --output /dev/null --silent --head --fail $url/mfpconsole); do
        printf '.'
        sleep 5
      done
      exit
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
