---
stages:
- name: RegisterApp
  inputs:
  - url: https://git.ng.bluemix.net/shinoj.zacharias/MFPApps.git
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.10.48, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.4.5, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      # To use Node.js 6.7.0, uncomment the following line:
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      echo "#### npm install -g mfpdev-cli"
      npm install -g mfpdev-cli
      echo "#### mfpdev --version"
      mfpdev --version
      cd ResourceRequestAndroid
      echo "#### adding server definition"
      mfpdev server add server1 --url 'http://mobilefoundation-ibmbank0cde-server.mybluemix.net:80' --login 'admin' --password 'gAlilei$fr' --setdefault
      echo "#### mfpdev app register"
      mfpdev app register
      curl --help
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
